### ISSUE TITLE
Cannot train on multiple GPUs

### ISSUE THREAD

**Issue by johann-petrak** [asahi417/tner#20]
When running training on multiple GPUs I get:

```
2022-06-29 20:34:39 INFO     [training completed, 1241.1814272403717 sec in total]
Traceback (most recent call last):
  File "train01.py", line 11, in <module>
    trainer.train(monitor_validation=True)
  File "/home/johann/software/anaconda3/envs/tner/lib/python3.8/site-packages/tner/model.py", line 324, in train
    self.model.save_pretrained(self.args.checkpoint_dir)
  File "/home/johann/software/anaconda3/envs/tner/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'save_pretrained'
```

This happens with torch 1.12.0+cu113

**Comment by asahi417** [comment]
I have fixed this shortly so please try to install the latest version of tner from the repo. I will add this to the next version.
